package com.woolenstorm.musicplayer

const val KEY_IS_SHUFFLING = "KEY_IS_SHUFFLING"
const val KEY_ID = "KEY_ID"
const val KEY_TITLE = "KEY_TITLE"
const val KEY_ARTIST = "KEY_ARTIST"
const val KEY_IS_SONG_CHOSEN = "KEY_IS_SONG_CHOSEN"
const val KEY_URI = "KEY_URI"
const val KEY_IS_PLAYING = "KEY_IS_PLAYING"
const val KEY_CURRENT_POSITION = "KEY_CURRENT_POSITION"
const val KEY_ALBUM_ARTWORK = "KEY_ALBUM_ARTWORK"
const val CHANNEL_ID = "musicPlayerNotificationChannel"
const val KEY_CURRENT_INDEX = "KEY_CURRENT_INDEX"
const val KEY_TIMESTAMP = "KEY_TIMESTAMP"
const val KEY_DURATION = "KEY_DURATION"
const val KEY_ALBUM = "KEY_ALBUM"
const val KEY_IS_HOMESCREEN = "KEY_IS_HOMESCREEN"